<template>
  <div class="min-h-screen bg-gray-50 py-8">
    <div class="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
      <!-- Header -->
      <div class="text-center mb-8">
        <h1 class="text-3xl font-bold text-gray-900">Create Organization</h1>
        <p class="mt-2 text-gray-600">Create a new organization with an invite code</p>
      </div>

      <!-- Invite Code Section (only show if user has permission) -->
      <div v-if="hasInvitePermission" class="bg-white rounded-lg shadow p-6 mb-6">
        <h2 class="text-xl font-semibold text-gray-900 mb-4">Step 1: Generate Invite Code for Others</h2>
        <div class="bg-blue-50 border border-blue-200 rounded-md p-4 mb-4">
          <div class="flex">
            <div class="flex-shrink-0">
              <svg class="h-5 w-5 text-blue-400" viewBox="0 0 20 20" fill="currentColor">
                <path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7-4a1 1 0 11-2 0 1 1 0 012 0zM9 9a1 1 0 000 2v3a1 1 0 001 1h1a1 1 0 100-2v-3a1 1 0 00-1-1H9z" clip-rule="evenodd" />
              </svg>
            </div>
            <div class="ml-3">
              <h3 class="text-sm font-medium text-blue-800">
                Important: You need an invite code from someone else
              </h3>
              <div class="mt-2 text-sm text-blue-700">
                <p>You cannot create an organization with your own invite code. Only users with existing organizations or admin/moderator privileges can generate invite codes.</p>
              </div>
            </div>
          </div>
        </div>
        
        <div class="flex items-center space-x-4">
          <button
            @click="generateInviteCode"
            :disabled="loading"
            class="bg-blue-600 text-white px-4 py-2 rounded-md hover:bg-blue-700 disabled:opacity-50"
          >
            {{ loading ? 'Generating...' : 'Generate Invite Code (If You Have Permission)' }}
          </button>
          <div v-if="inviteCode" class="flex items-center space-x-2">
            <span class="text-sm text-gray-600">Invite code to share:</span>
            <code class="bg-gray-100 px-2 py-1 rounded text-sm font-mono">{{ inviteCode }}</code>
            <button
              @click="copyInviteCode"
              class="text-blue-600 hover:text-blue-800 text-sm"
            >
              Copy
            </button>
          </div>
        </div>
        <p class="text-sm text-gray-500 mt-2">
          Only users with existing organizations or admin/moderator privileges can generate invite codes. If you don't have permission, ask someone who does to generate an invite code for you.
        </p>
      </div>

      <!-- Permission Info for users without invite permission -->
      <div v-if="!checkingPermission && !hasInvitePermission" class="bg-yellow-50 border border-yellow-200 rounded-md p-4 mb-6">
        <div class="flex">
          <div class="flex-shrink-0">
            <svg class="h-5 w-5 text-yellow-400" viewBox="0 0 20 20" fill="currentColor">
              <path fill-rule="evenodd" d="M8.257 3.099c.765-1.36 2.722-1.36 3.486 0l5.58 9.92c.75 1.334-.213 2.98-1.742 2.98H4.42c-1.53 0-2.493-1.646-1.743-2.98l5.58-9.92zM11 13a1 1 0 11-2 0 1 1 0 012 0zm-1-8a1 1 0 00-1 1v3a1 1 0 002 0V6a1 1 0 00-1-1z" clip-rule="evenodd" />
            </svg>
          </div>
          <div class="ml-3">
            <h3 class="text-sm font-medium text-yellow-800">
              You cannot generate invite codes
            </h3>
            <div class="mt-2 text-sm text-yellow-700">
              <p>{{ permissionReason }}. You need an invite code from someone else to create an organization.</p>
            </div>
          </div>
        </div>
      </div>

      <!-- Organization Form -->
      <div class="bg-white rounded-lg shadow p-6">
        <h2 class="text-xl font-semibold text-gray-900 mb-4">
          {{ hasInvitePermission ? 'Step 2: Create Organization' : 'Step 1: Create Organization' }}
        </h2>
        
        <form @submit.prevent="createOrganization" class="space-y-6">
          <!-- Invite Code Input -->
          <div>
            <label for="inviteCode" class="block text-sm font-medium text-gray-700">
              Invite Code from Someone Else *
            </label>
            <input
              id="inviteCode"
              v-model="form.inviteCode"
              type="text"
              required
              class="mt-1 block w-full border-gray-300 rounded-md shadow-sm focus:ring-blue-500 focus:border-blue-500 sm:text-sm"
              placeholder="Enter invite code from another user"
            />
            <p class="mt-1 text-sm text-gray-500">
              This must be an invite code generated by someone else, not your own.
            </p>
          </div>

          <!-- Basic Information -->
          <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
            <div>
              <label for="title" class="block text-sm font-medium text-gray-700">
                Organization Name *
              </label>
              <input
                id="title"
                v-model="form.title"
                type="text"
                required
                class="mt-1 block w-full border-gray-300 rounded-md shadow-sm focus:ring-blue-500 focus:border-blue-500 sm:text-sm"
                placeholder="e.g., Cache Valley Tech Community"
              />
            </div>

            <div>
              <label for="slug" class="block text-sm font-medium text-gray-700">
                URL Slug *
              </label>
              <input
                id="slug"
                v-model="form.slug"
                type="text"
                required
                class="mt-1 block w-full border-gray-300 rounded-md shadow-sm focus:ring-blue-500 focus:border-blue-500 sm:text-sm"
                placeholder="e.g., cache-valley-tech"
              />
            </div>
          </div>

          <div>
            <label for="summary" class="block text-sm font-medium text-gray-700">
              Summary *
            </label>
            <textarea
              id="summary"
              v-model="form.summary"
              required
              rows="3"
              class="mt-1 block w-full border-gray-300 rounded-md shadow-sm focus:ring-blue-500 focus:border-blue-500 sm:text-sm"
              placeholder="Brief description of your organization"
            ></textarea>
          </div>

          <!-- Organization Type and Location -->
          <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
            <div>
              <label for="type" class="block text-sm font-medium text-gray-700">
                Organization Type
              </label>
              <select
                id="type"
                v-model="form.type"
                class="mt-1 block w-full border-gray-300 rounded-md shadow-sm focus:ring-blue-500 focus:border-blue-500 sm:text-sm"
              >
                <option value="community">Community</option>
                <option value="action">Action Group</option>
                <option value="political">Political</option>
                <option value="religious">Religious</option>
                <option value="business">Business</option>
                <option value="nonprofit">Nonprofit</option>
                <option value="educational">Educational</option>
                <option value="social">Social</option>
                <option value="other">Other</option>
              </select>
            </div>

            <div>
              <label for="primaryLocation" class="block text-sm font-medium text-gray-700">
                Primary Location
              </label>
              <select
                id="primaryLocation"
                v-model="form.primary_location"
                class="mt-1 block w-full border-gray-300 rounded-md shadow-sm focus:ring-blue-500 focus:border-blue-500 sm:text-sm"
              >
                <option value="remote">Remote</option>
                <option value="address">Physical Address</option>
                <option value="space">Shared Space</option>
                <option value="virtual">Virtual</option>
                <option value="hybrid">Hybrid</option>
              </select>
            </div>
          </div>

          <!-- Location Details -->
          <div v-if="form.primary_location === 'address'" class="grid grid-cols-1 md:grid-cols-2 gap-6">
            <div>
              <label for="locationAddress" class="block text-sm font-medium text-gray-700">
                Address
              </label>
              <input
                id="locationAddress"
                v-model="form.location_address"
                type="text"
                class="mt-1 block w-full border-gray-300 rounded-md shadow-sm focus:ring-blue-500 focus:border-blue-500 sm:text-sm"
                placeholder="123 Main St, City, State 12345"
              />
            </div>
          </div>

          <div v-if="form.primary_location === 'space'" class="grid grid-cols-1 md:grid-cols-2 gap-6">
            <div>
              <label for="locationSpace" class="block text-sm font-medium text-gray-700">
                Space Name
              </label>
              <input
                id="locationSpace"
                v-model="form.location_space"
                type="text"
                class="mt-1 block w-full border-gray-300 rounded-md shadow-sm focus:ring-blue-500 focus:border-blue-500 sm:text-sm"
                placeholder="e.g., Community Center, Library Meeting Room"
              />
            </div>
          </div>

          <!-- About and Goals -->
          <div>
            <label for="about" class="block text-sm font-medium text-gray-700">
              About
            </label>
            <textarea
              id="about"
              v-model="form.about"
              rows="4"
              class="mt-1 block w-full border-gray-300 rounded-md shadow-sm focus:ring-blue-500 focus:border-blue-500 sm:text-sm"
              placeholder="Tell us more about your organization..."
            ></textarea>
          </div>

          <div>
            <label for="goals" class="block text-sm font-medium text-gray-700">
              Goals
            </label>
            <textarea
              id="goals"
              v-model="form.goals"
              rows="3"
              class="mt-1 block w-full border-gray-300 rounded-md shadow-sm focus:ring-blue-500 focus:border-blue-500 sm:text-sm"
              placeholder="What are your organization's main goals?"
            ></textarea>
          </div>

          <!-- Website and Social Links -->
          <div>
            <label for="website" class="block text-sm font-medium text-gray-700">
              Website
            </label>
            <input
              id="website"
              v-model="form.website"
              type="url"
              class="mt-1 block w-full border-gray-300 rounded-md shadow-sm focus:ring-blue-500 focus:border-blue-500 sm:text-sm"
              placeholder="https://example.com"
            />
          </div>

          <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
            <div>
              <label for="socialFacebook" class="block text-sm font-medium text-gray-700">
                Facebook URL
              </label>
              <input
                id="socialFacebook"
                v-model="form.social_facebook"
                type="url"
                class="mt-1 block w-full border-gray-300 rounded-md shadow-sm focus:ring-blue-500 focus:border-blue-500 sm:text-sm"
                placeholder="https://facebook.com/yourpage"
              />
            </div>

            <div>
              <label for="socialTwitter" class="block text-sm font-medium text-gray-700">
                Twitter URL
              </label>
              <input
                id="socialTwitter"
                v-model="form.social_twitter"
                type="url"
                class="mt-1 block w-full border-gray-300 rounded-md shadow-sm focus:ring-blue-500 focus:border-blue-500 sm:text-sm"
                placeholder="https://twitter.com/yourhandle"
              />
            </div>
          </div>

          <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
            <div>
              <label for="socialLinkedin" class="block text-sm font-medium text-gray-700">
                LinkedIn URL
              </label>
              <input
                id="socialLinkedin"
                v-model="form.social_linkedin"
                type="url"
                class="mt-1 block w-full border-gray-300 rounded-md shadow-sm focus:ring-blue-500 focus:border-blue-500 sm:text-sm"
                placeholder="https://linkedin.com/company/yourcompany"
              />
            </div>

            <div>
              <label for="socialInstagram" class="block text-sm font-medium text-gray-700">
                Instagram URL
              </label>
              <input
                id="socialInstagram"
                v-model="form.social_instagram"
                type="url"
                class="mt-1 block w-full border-gray-300 rounded-md shadow-sm focus:ring-blue-500 focus:border-blue-500 sm:text-sm"
                placeholder="https://instagram.com/yourhandle"
              />
            </div>
          </div>

          <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
            <div>
              <label for="discordUrl" class="block text-sm font-medium text-gray-700">
                Discord URL
              </label>
              <input
                id="discordUrl"
                v-model="form.discord_url"
                type="url"
                class="mt-1 block w-full border-gray-300 rounded-md shadow-sm focus:ring-blue-500 focus:border-blue-500 sm:text-sm"
                placeholder="https://discord.gg/yourinvite"
              />
            </div>

            <div>
              <label for="slackUrl" class="block text-sm font-medium text-gray-700">
                Slack URL
              </label>
              <input
                id="slackUrl"
                v-model="form.slack_url"
                type="url"
                class="mt-1 block w-full border-gray-300 rounded-md shadow-sm focus:ring-blue-500 focus:border-blue-500 sm:text-sm"
                placeholder="https://yourworkspace.slack.com"
              />
            </div>
          </div>

          <!-- Submit Button -->
          <div class="flex justify-end">
            <button
              type="submit"
              :disabled="loading || !form.inviteCode"
              class="bg-green-600 text-white px-6 py-2 rounded-md hover:bg-green-700 disabled:opacity-50"
            >
              {{ loading ? 'Creating...' : 'Create Organization' }}
            </button>
          </div>
        </form>
      </div>

      <!-- Success Message -->
      <div v-if="successMessage" class="mt-6 bg-green-50 border border-green-200 rounded-md p-4">
        <div class="flex">
          <div class="flex-shrink-0">
            <svg class="h-5 w-5 text-green-400" viewBox="0 0 20 20" fill="currentColor">
              <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clip-rule="evenodd" />
            </svg>
          </div>
          <div class="ml-3">
            <h3 class="text-sm font-medium text-green-800">
              Organization Created Successfully!
            </h3>
            <div class="mt-2 text-sm text-green-700">
              <p>{{ successMessage }}</p>
            </div>
          </div>
        </div>
      </div>

      <!-- Error Message -->
      <div v-if="errorMessage" class="mt-6 bg-red-50 border border-red-200 rounded-md p-4">
        <div class="flex">
          <div class="flex-shrink-0">
            <svg class="h-5 w-5 text-red-400" viewBox="0 0 20 20" fill="currentColor">
              <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zM8.707 7.293a1 1 0 00-1.414 1.414L8.586 10l-1.293 1.293a1 1 0 101.414 1.414L10 11.414l1.293 1.293a1 1 0 001.414-1.414L11.414 10l1.293-1.293a1 1 0 00-1.414-1.414L10 8.586 8.707 7.293z" clip-rule="evenodd" />
            </svg>
          </div>
          <div class="ml-3">
            <h3 class="text-sm font-medium text-red-800">
              Error
            </h3>
            <div class="mt-2 text-sm text-red-700">
              <p>{{ errorMessage }}</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, reactive, onMounted } from 'vue'
import { useRouter } from 'vue-router'
import { ApiService } from '../services/api'

const router = useRouter()

// Reactive data
const loading = ref(false)
const inviteCode = ref('')
const successMessage = ref('')
const errorMessage = ref('')
const hasInvitePermission = ref(false)
const permissionReason = ref('')
const checkingPermission = ref(true)

const form = reactive({
  inviteCode: '',
  title: '',
  slug: '',
  summary: '',
  type: 'community',
  primary_location: 'remote',
  location_address: '',
  location_space: '',
  about: '',
  goals: '',
  website: '',
  social_facebook: '',
  social_twitter: '',
  social_linkedin: '',
  social_instagram: '',
  social_youtube: '',
  discord_url: '',
  slack_url: ''
})

// Methods
const checkInvitePermission = async () => {
  try {
    checkingPermission.value = true
    const response = await ApiService.checkInvitePermission()
    hasInvitePermission.value = response.data.hasPermission
    permissionReason.value = response.data.reason
  } catch (error: any) {
    console.error('Error checking invite permission:', error)
    hasInvitePermission.value = false
    permissionReason.value = 'Unable to check permissions'
  } finally {
    checkingPermission.value = false
  }
}

const generateInviteCode = async () => {
  try {
    loading.value = true
    errorMessage.value = ''
    
    const response = await ApiService.generateInviteCode()
    inviteCode.value = response.data.inviteCode
    // Don't auto-fill the form - this code is for sharing with others
  } catch (error: any) {
    errorMessage.value = error.response?.data?.error || 'Failed to generate invite code'
  } finally {
    loading.value = false
  }
}

const copyInviteCode = async () => {
  try {
    await navigator.clipboard.writeText(inviteCode.value)
    // You could add a toast notification here
  } catch (error) {
    console.error('Failed to copy invite code:', error)
  }
}

const createOrganization = async () => {
  try {
    loading.value = true
    errorMessage.value = ''
    successMessage.value = ''
    
    const response = await ApiService.createOrganization(form)
    successMessage.value = response.message
    
    // Reset form
    Object.keys(form).forEach(key => {
      if (key !== 'inviteCode') {
        form[key as keyof typeof form] = ''
      }
    })
    
    // Redirect to dashboard after 3 seconds
    setTimeout(() => {
      router.push('/dashboard')
    }, 3000)
  } catch (error: any) {
    console.error('Error creating organization:', error)
    errorMessage.value = error.response?.data?.error || 'Failed to create organization'
  } finally {
    loading.value = false
  }
}

// Check permissions when component mounts
onMounted(() => {
  checkInvitePermission()
})
</script>
